### ISSUE TITLE
Can't generate dart lib on fedora

### ISSUE THREAD

**Issue by MalcolmMielle** [CoVital-Project/node-mongo-backend-spike#64]
Hi all,

On a clean clone of the repo on my Fedora 31 machine I'm hit this error:

```
$ make dart_client 
env OUTPUT_LANGUAGE=dart ./script/generate-bindings.sh

******************************************************
*
* Building dart client.
*  input schema: reference/pulseox-data-collector.v1.json
*  output folder: clients/dart
*
******************************************************
[error] The spec file is not found: /local/reference/pulseox-data-collector.v1.json
[error] Check the path of the OpenAPI spec and try again.
make: *** [Makefile:4: dart_client] Error 1
```

Not sure what to do about it since I've never worked with docker before. It seems like the ${PWD} command is not really understood since it stays with a weird local instead of my actual path?

**Comment by haggy** [comment]
The full command is:
```bash
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
    -i /local/${SCHEMA} \
    -g "${OUTPUT_LANGUAGE}" \
    -o "/local/clients/${OUTPUT_LANGUAGE}"
```
It's mounting `${PWD}` as `/local` in the container so that the openapi generator can access the spec file. This works on Mac OSX so Im thinking it's a weird docker FS mount issue with Fedora.

As a workaround, can you try installing the generator "directly" using NPM?
`npm install @openapitools/openapi-generator-cli -g`

You can then try to run:
```bash
openapi-generator generate \
    -i reference/pulseox-data-collector.v1.json \
    -g dart \
    -o "/clients/dart"
```

**Comment by MalcolmMielle** [comment]
That seems to have worked! I've add to do a couple more steps but they were well indicated after (and manually create the folder clients/dart)
